kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: ico-landing
  name: ico-landing
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ico-landing
  template:
    metadata:
      labels:
        k8s-app: ico-landing
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: ico-landing
          image: gcr.io/xxcloud/ico-landing-dev:fae5332             
          env:            
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TZ                                                                                                                                                                                                                                         
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: ico-landing
  name: ico-landing
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: ico-landing